server:
  port: 8761 # Port du serveur Eureka

eureka:
  client:
    register-with-eureka: false # Le serveur ne s'enregistre pas lui-même
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # Réduit le délai d'attente
